#!/bin/sh

# I was lazy enough to create my own package of terraform or packer currently
# and i was wondering if i have to switch from multiple version of the same software ...

# set -x

# read argument
if [ -z "$1" ]
then
  echo "No argument"
  echo "usage : ${0} <SOFTWARE ZIP FILE>"
  echo "example : ${0} packer_0.12.2_linux_amd64.zip"
  exit 1
fi

func print_exit () {
    echo $1
    exit 1
}

func check_exec () {
  if [ ! -f $1 ] || [ ! -x $1 ]
  then
    print_exit "$1:  no such command"
  fi
}

# Testing unzip presence
UNZIP="/usr/bin/unzip"
check_exec $UNZIP

UPDATE_ALTERNATIVES="/usr/bin/update-alternatives"
check_exec $UPDATE_ALTERNATIVES

# Getting software name
# (Hoping they won't change the prefix in the future)

SOFT2MANAGE=$( echo "${1}" | awk -F "_" '{print $1}' )
SOFTVERSION=$( echo "${1}" | awk -F "_" '{print $2}' )

# Version exist already ?
if [ -f "/usr/local/bin/${SOFT2MANAGE}_${SOFTVERSION}" ]
then
    print_exit "This version already exist"
fi

# Wondering if i can do something less "dirty" ?
$UNZIP -jp "${1}" "${SOFT2MANAGE}" | cat > "/usr/local/bin/${SOFT2MANAGE}_${SOFTVERSION}"
chmod 0775 "/usr/local/bin/${SOFT2MANAGE}_${SOFTVERSION}"

# Getting current number of software
SOFTNUMBERS=$( find /usr/local/bin/ -xdev -type f -name "${SOFT2MANAGE}_*" | wc -l )
SOFTNUMBERS=$((SOFTNUMBERS + 1))

# Finally updating
$UPDATE_ALTERNATIVES --verbose --install "/usr/local/bin/${SOFT2MANAGE}" "${SOFT2MANAGE}" "/usr/local/bin/${SOFT2MANAGE}_${SOFTVERSION}" "${SOFTNUMBERS}"

exit 0
